name: Python Web App to Azure

on:
  push:
    branches:
      - main  # Set this to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Match your runtime

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Add tests here

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: flask-cers-app-erfgc2aechc9f7cc  # Must match Azure app service name!
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE2 }}
          package: .
